### ISSUE TITLE
[Feat] UI 및 플로우 수정

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-TrendMedia#4]
## Todo
- [ ] 온보딩 UI 수정 
- [ ] 온보딩 > 메인 > 디테일 에 맞게 앱 플로우 정리 (화면 전환)
- [ ] 앱 전체 UI 통일성 있게 수정 
- [ ] 클로저로 화면 전환 코드 작성 
- [ ] 데이터 전달 (클로저/Notification)
